// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj_xD-9CwITutsyC0pZPq2O_GYobiBb8o',
    appId: '1:542089691589:web:9f30ec896967d6150dcbac',
    messagingSenderId: '542089691589',
    projectId: 'privet-tutor',
    authDomain: 'privet-tutor.firebaseapp.com',
    storageBucket: 'privet-tutor.appspot.com',
    measurementId: 'G-XYH2ZRRDD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCnSCEJXrzGdQA75j2cQ1vBNvxH66CdXo',
    appId: '1:542089691589:android:2975414a42395ae00dcbac',
    messagingSenderId: '542089691589',
    projectId: 'privet-tutor',
    storageBucket: 'privet-tutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFDsOSRJ453FpL0Gl7X0rZaueswduvDQ',
    appId: '1:542089691589:ios:56a979d7817be0fa0dcbac',
    messagingSenderId: '542089691589',
    projectId: 'privet-tutor',
    storageBucket: 'privet-tutor.appspot.com',
    iosBundleId: 'com.example.privetTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFDsOSRJ453FpL0Gl7X0rZaueswduvDQ',
    appId: '1:542089691589:ios:093a3dfd26ab282c0dcbac',
    messagingSenderId: '542089691589',
    projectId: 'privet-tutor',
    storageBucket: 'privet-tutor.appspot.com',
    iosBundleId: 'com.example.privetTutor.RunnerTests',
  );
}
